# Generated by Django 2.1b1 on 2018-07-28 17:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('arriving_time', models.TimeField(choices=[(datetime.time(1, 0), '1:00 am'), (datetime.time(2, 0), '2:00 am'), (datetime.time(3, 0), '3:00 am'), (datetime.time(4, 0), '4:00 am'), (datetime.time(5, 0), '5:00 am'), (datetime.time(6, 0), '6:00 am'), (datetime.time(7, 0), '7:00 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(10, 0), '10:00 am'), (datetime.time(11, 0), '11:00 am'), (datetime.time(12, 0), '12:00 pm'), (datetime.time(13, 0), '1:00 pm'), (datetime.time(14, 0), '2:00 pm'), (datetime.time(15, 0), '3:00 pm'), (datetime.time(16, 0), '4:00 pm'), (datetime.time(17, 0), '5:00 pm'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(21, 0), '9:00 pm'), (datetime.time(22, 0), '10:00 pm'), (datetime.time(23, 0), '11:00 pm'), (datetime.time(0, 0), '12:00 am')])),
                ('departure_time', models.TimeField(choices=[(datetime.time(1, 0), '1:00 am'), (datetime.time(2, 0), '2:00 am'), (datetime.time(3, 0), '3:00 am'), (datetime.time(4, 0), '4:00 am'), (datetime.time(5, 0), '5:00 am'), (datetime.time(6, 0), '6:00 am'), (datetime.time(7, 0), '7:00 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(10, 0), '10:00 am'), (datetime.time(11, 0), '11:00 am'), (datetime.time(12, 0), '12:00 pm'), (datetime.time(13, 0), '1:00 pm'), (datetime.time(14, 0), '2:00 pm'), (datetime.time(15, 0), '3:00 pm'), (datetime.time(16, 0), '4:00 pm'), (datetime.time(17, 0), '5:00 pm'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(21, 0), '9:00 pm'), (datetime.time(22, 0), '10:00 pm'), (datetime.time(23, 0), '11:00 pm'), (datetime.time(0, 0), '12:00 am')])),
                ('fare', models.IntegerField()),
                ('source', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('date_of_journey', models.DateField()),
                ('no_of_seats', models.IntegerField(default=60)),
                ('available_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PassengerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('seat_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=128)),
                ('phone_no', models.CharField(max_length=20)),
                ('no_of_tickets', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.BusInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='passengerinfo',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TicketInfo'),
        ),
    ]
